-- CRM Tablespace
CREATE TABLESPACE crm_data DATAFILE 'crm_data01.dbf' SIZE 200M AUTOEXTEND ON;
CREATE TABLESPACE bronze DATAFILE 'bronze_data01.dbf' SIZE 200M AUTOEXTEND ON;

-- ERP Tablespace
CREATE TABLESPACE erp_data DATAFILE 'erp_data01.dbf' SIZE 200M AUTOEXTEND ON;
CREATE TABLESPACE silver DATAFILE 'silver_data01.dbf' SIZE 200M AUTOEXTEND ON;

CREATE TABLESPACE gold DATAFILE 'gold_data01.dbf' SIZE 200M AUTOEXTEND ON;

SELECT file_name
FROM dba_data_files;

-- CREATE USER crm IDENTIFIED BY 12345
--   DEFAULT TABLESPACE crm_data
--   QUOTA UNLIMITED ON crm_data;

-- CREATE USER erp IDENTIFIED BY 12345
--   DEFAULT TABLESPACE erp_data
--   QUOTA UNLIMITED ON erp_data;
  
  
CREATE USER bronze IDENTIFIED BY 12345
  DEFAULT TABLESPACE bronze
  QUOTA UNLIMITED ON bronze;

CREATE USER silver IDENTIFIED BY 12345
  DEFAULT TABLESPACE silver
  QUOTA UNLIMITED ON silver;
  
CREATE USER gold IDENTIFIED BY 12345
  DEFAULT TABLESPACE gold
  QUOTA UNLIMITED ON gold;


-- Common role for app users
CREATE ROLE app_role;

-- Assign normal privileges
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO app_role;

-- Grant role to users
GRANT app_role TO crm;
GRANT app_role TO erp;

GRANT app_role TO bronze;
GRANT app_role TO silver;
GRANT app_role TO gold;


SELECT * FROM all_users
WHERE username IN ('BRONZE', 'SILVER', 'GOLD');
